runtime: php55
api_version: 1

handlers:  
- url: /(.+\.(eot|ttf|woff|woff2)$
  static_files: fonts/\1
  upload: .+\.(eot|ttf|woff|woff2)$
  
- url: /(.+\.(bmp|gif|ico|jpeg|jpg|png))$
  static_files: img/\1
  upload: .+\.(bmp|gif|ico|jpeg|jpg|png)$
  application_readable: true

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: js/\1
  upload: js/(.*\.js)
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /.*
  upload: index.html
  static_files: index.html
