runtime: php55
api_version: 1

handlers:  
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts

- url: /font-awesome
  static_dir: font-awesome
 
- url: /js
  static_dir: js

- url: /.*
  upload: index.html
  static_files: index.html
